# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:            HopeFaith TV
email:            hopefaithtvministry@gmail.com
description:      Sharing the Hope, Faith and Truth of the Gospel of Jesus Christ
baseurl:          '' # The subpath of your site, e.g. /blog
url:              'https://hopefaithtv.github.io/hopefaith/' # The base hostname & protocol for your site
twitter_username: HopeFaithTV
facebook_username: HopeFaithTV-1635543393125902

markdown:  kramdown
permalink: pretty
paginate:  12
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  ahmad:
    name:             HopeFaith TV
    bio:              Sharing the Hope, Faith and Truth of the Gospel of Jesus Christ.
    gravatar:         https://s.gravatar.com/avatar/f83141edd9e6339e678648596a403fd5?s=150
    email:            hopefaithtvministry@gmail.com
    website:          http://hopefaithtv.com
    twitter_username: HopeFaithTV
    facebook_username: HopeFaithTV-1635543393125902
    
